### ISSUE TITLE
Alternative IMAP client

### ISSUE THREAD

**Issue by andris9** [klenty/imap#3]
I'm sorry to butt in, but just in case you'd be looking for a more modern and complete alternative for accessing IMAP, then I have built a module called [ImapFlow](https://imapflow.com/) that can do anything `node-imap` and `imap-simple` can do, with a simpler interface (full _async_..._await_ support, IMAP protocol is abstracted away so no need to know about FETCH keywords etc.).

**Comment by shashankklenty** [comment]
> I'm sorry to butt in, but just in case you'd be looking for a more modern and complete alternative for accessing IMAP, then I have built a module called [ImapFlow](https://imapflow.com/) that can do anything `node-imap` and `imap-simple` can do, with a simpler interface (full _async_..._await_ support, IMAP protocol is abstracted away so no need to know about FETCH keywords etc.).

Hey, your suggestion is much appreciated.

We actually had that library under our radar. However the reason we do not shift modules is that the issues we are facing with libraries are not their API support or usability, but their parser's capabilities. From what we've seen in production the popular IMAP modules people use eventually fail to parse some responses that come from a variety of different email boxes that our users come with. We have yet to do a lot of testing with ImapFlow before we can shift, but we will definitely consider it!

Closing this issue for now.

**Comment by andris9** [comment]
Thanks for the feedback! ImapFlows parser is battle tested and really solid, for example it powers the EmailEngine.app application that handles tons of different kind of IMAP servers. The parsers for ImapFlow and node-imap are also completely different as ImapFlow is not regex based like node-imap is.

**Comment by shashankklenty** [comment]
> The parsers for ImapFlow and node-imap are also completely different as ImapFlow is not regex based like node-imap is.

This is perfect! We'll definitely consider trying it out and migrating code now :)
